//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDemographicsRepository.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PatientDataEntities : DbContext
    {
        public PatientDataEntities()
            : base("name = PatientDataEntities ")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<PatientRecord> PatientRecords { get; set; }
    }
}
